var n = 100;
var m = 11;
var sum = n + m;
var differnce = m - n;
var multiplication = n * m;
var division = n / m;
var divisor = n % m;
// console.log(sum);
// console.log(division);
console.log(divisor);
